### PR TITLE
Don't merge - Adjust GraphQL introspection to fit graph.cool service

### PR DESCRIPTION
**Pull request by mulyoved**
Just a quick hack to make it work with https://www.graph.cool/

Seem to work for sample Post table on all operation, including 
- list, sort and filter
- create, edit, delete

Still need to:
- [ ] more testing on more complex data, enums and such
- [ ] adjust unit tests

Maybe for now just include a link in readme about this fork for those care about graph.cool

---
This change is [Reviewable](https://reviewable.io/reviews/marmelab/aor-simple-graphql-client/25)

### CODE REVIEW

**Comment by djhi** [comment]
Nice! Thanks for building a graphcool client! However, as this is a radically different client, I suggest you make a pull request on the admin-on-rest repository to include it in the [documentation](https://github.com/marmelab/admin-on-rest/blob/master/docs/RestClients.md). I will also add a note in this client readme about yours.

**Comment by djhi** [comment]
just so you know, I'm refactoring a lot to allow easier implementation of different graphql flavors. Should be ready before friday ;)

**Comment by mulyoved** [comment]
Cool, will love to convert my code to a usage example

**Comment by djhi** [comment]
Not that simple ^^

But you'll just have to supply a "flavor" definition so your package might just include mine and configure it with the graphcool flavor (define the operations names, how to map parameters, how to parse response, etc.)

**Comment by djhi** [comment]
You can see the proposed flavor definition in #35

**Pull request closed without merging**
